class CreateChatTimesheets < ActiveRecord::Migration[5.2]
  def up
    execute(<<~SQL)
      create table chat_timesheets (
        id bigint generated by default as identity primary key,
        client_start timestamptz,
        pro_start timestamptz,
        end_time timestamptz,
        ot_events jsonb,
        chat_id bigint not null,
        chat_type text not null,
        created_at timestamptz not null default now(),
        updated_at timestamptz not null default now(),
        unique (chat_id, chat_type)
      );

      create index on chat_timesheets (chat_id);
      create index on chat_timesheets (chat_type);
    SQL
  end

  def down
    execute(<<~SQL)
      drop table chat_timesheets;
    SQL
  end
end
