class MoveSmsConfigIntoDb < ActiveRecord::Migration[5.2]
  def up
    execute(<<~SQL)
      create table sms_settings (
        id bigint generated by default as identity primary key,
        api_key text not null,
        api_secret text not null,
        phone_number text not null,
        created_at timestamptz not null default now(),
        updated_at timestamptz not null default now()
      )
    SQL
  end

  def down
    execute(<<~SQL)
      drop table sms_settings;
    SQL
  end
end
