class CreateAdminPermissions < ActiveRecord::Migration[5.2]
  def up
    execute(<<~SQL)
      create table admin_permissions (
        id bigint generated by default as identity primary key,
        admin_user_id bigint not null references admin_users unique,
        super_admin boolean not null default false,

        cms_create boolean not null default false,
        cms_edit boolean not null default false,
        cms_delete boolean not null default false,

        blog_create boolean not null default false,
        blog_edit boolean not null default false,
        blog_delete boolean not null default false,

        created_at timestamptz not null default now(),
        updated_at timestamptz not null default now()
      );

      create index on admin_permissions (admin_user_id);

      insert into admin_permissions (
        admin_user_id,
        super_admin,
        cms_create,
        cms_edit,
        cms_delete,
        blog_create,
        blog_edit,
        blog_delete
      )
        select id, true, true, true, true, true, true, true
      from admin_users;
    SQL
  end

  def down
    execute(<<~SQL)
      drop table admin_permissions;
    SQL
  end
end
